accounts/urls.py
from django.urls import path, re_path
from django.urls import reverse_lazy
from .views import register, password_change, UserProfile
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
	path('register/', register, name='register'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout', kwargs={'next_page':'writersapp:home'}),
	path('password/', password_change, name="password_change"),
	path('profile/', UserProfile.as_view(), name="profile"),
]

writers/urls.py
from django.contrib import admin
from django.urls import path, include

from writersapp.views import PostListView

urlpatterns = [
	path('',PostListView.as_view(), name='home'),
	path('post/', include('writersapp.urls', namespace='writersapp')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    # path('accounts/', include('accounts.passwords.urls')),
]

writersapp/urls.py
from django.urls import path 

from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, DraftListView, PostPublishView,PostPublishedview, CommentView

app_name = "writersapp"

urlpatterns = [
	# path('', PostDetailView.as_view(), name='post_list'),
	path('detail/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
	path('create/', PostCreateView.as_view(), name='post_create'),
	path('drafts/', DraftListView.as_view(), name='drafts'),
	path('update/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
	path('publish/<int:pk>/', PostPublishView.as_view(), name='post_publish'),
	path('published/list/', PostPublishedview.as_view(), name='published'),
	path('delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),
	path('comment/<int:pk>/', CommentView.as_view(), name='comment_create'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django import forms

class SignupForm(UserCreationForm):
	
	class Meta:
		model = get_user_model()
		fields = ('username', 'email')

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		field_class = "form-control, form_create"
		self.fields['username'].widget.attrs.update({"placeholder": "Username", "id":"id_signup", "class": field_class})
		self.fields['email'].widget.attrs.update({"required":True,"placeholder": "example@gmail.com","class": field_class})
		self.fields['password1'].widget.attrs.update({"placeholder": "Password","class": field_class})
		self.fields['password2'].widget.attrs.update({"placeholder": "Confirm password","class": field_class})
		for fieldname in ['username', 'email','password1', 'password2']:
			self.fields[fieldname].help_text = None

class LoginForm(AuthenticationForm):

	class Meta:
		model = get_user_model()
		fields = ('username', 'password',)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		field_class = "form-control, form_create"
		self.fields['username'].widget.attrs.update({"placeholder": "Username","class": field_class})
		self.fields['password'].widget.attrs.update({"placeholder": "Password","class": field_class})

class ResetPasswordForm(PasswordChangeForm):
	class Meta:
		model = get_user_model()
		fields = ("old_password", "new_password1", "new_password2")
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)		
		field_class = "form-control, form_create"
		self.fields['old_password'].widget.attrs.update({"placeholder": "Old password","class": field_class})
		self.fields['new_password1'].widget.attrs.update({"placeholder": "New password","class": field_class})
		self.fields['new_password2'].widget.attrs.update({"placeholder": "Confirm new password","class": field_class})
		for fieldname in ['old_password', 'new_password1','new_password2']:
			self.fields[fieldname].help_text = None		

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView
from .forms import SignupForm, LoginForm, ResetPasswordForm
from writersapp.models import Post
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth import get_user_model, authenticate, login, logout, update_session_auth_hash
from django.contrib import messages


from django.urls import reverse_lazy
# Create your views here.

def register(request):
	if request.user.is_active:
		return HttpResponseRedirect("home")
	login_form = LoginForm()
	signup_form = SignupForm()
	is_user = True
	if request.method == "POST":
		if request.POST.get("email"):
			form = SignupForm(data=request.POST)
			if form.is_valid():
				user = form.save()	
				return HttpResponseRedirect(reverse_lazy("accounts:register"))
			else:
				signup_form = form
				is_user = False
		else:
			form = LoginForm(data=request.POST)
			if form.is_valid():
				username = request.POST.get("username")
				password = request.POST.get("password")
				user = authenticate(username=username, password=password)

				if user is not None:
					# if user.is_active:
					login(request, user)
					return HttpResponseRedirect(reverse_lazy("home"))
				else:
					print(user)
			if form.errors:
				login_form = form
	return render(request, 'accounts/register.html', {"login_form":login_form, "signup_form":signup_form, "is_user":is_user})

def password_change(request):
	if request.method == 'POST':
		form = ResetPasswordForm(request.user, request.POST)
		if form.is_valid():
			user = form.save()
			update_session_auth_hash(request,user)
			messages.success(request, 'Your password was successfully updated!')
			return redirect('home')
		else:
			messages.error(request, 'Please correct the error below.')
	else:
		form = ResetPasswordForm(request.user)
	return render(request, 'accounts/pass_reset.html', {
	'form': form
		})

class UserProfile(LoginRequiredMixin, ListView):
	model = get_user_model()
	login_url = "accounts:register"
	success_url = "home"
	template_name = "accounts/profile.html"

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    context["user_posts"] = Post.objects.filter(author=self.request.user)
	    context["drafts"] = Post.objects.filter(author=self.request.user, draft=True)
	    context["pub"] = Post.objects.filter(author=self.request.user, draft=False)
	    return context

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body_block %}
	<section class="home-bg">
		<div class="container">
		<div class="row">
			<div class="col-sm-5 rounded gradient shadow p-5 temp-margin mx-auto">
				<h4 class="text-center">Log In</h4>				
				<form class="user-form" method="POST">{% csrf_token %}
				  {% bootstrap_form form %}
				  <div class="text-center">
				    <button class="btn btn-custom" type="submit">Log in</button>
				    <p>Already have an account? <a href="{% url 'accounts:login' %}" class="card-link text-primary">Log in</a></p>
				  </div>
				</form>
				<div class="text-center py-1">
					<p class="shadow">Made with <i class="fa fa-heart text-danger"></i> by <strong>Brian Mwevi</strong><br>
						<a href="#" target="_blank" class="btn btn-md btn-custom text-dark">View on GitHub <i class="fa fa-external-link"></i></a>
					</p>
				</div>
			</div>
		</div>
	</div>
	</section>
{% endblock body_block %}

accounts/templates/accounts/pass_reset.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body_block %}
	
<section class="home-bg">
	<div class="container temp-margin">
		<div class="row">
			<div class="col-sm-5 mx-auto my-5">
				<div class="shadow gradient py-5 px-4 rounded">
					<h5 class="text-center pb-4">Changing password for {{ user.username|capfirst }}</h5>
					<form id="signupForm" action="{% url 'accounts:password_change' %}" method="POST">{% csrf_token %}
						{% bootstrap_form form %}
						<div class="text-center">
							<button class="btn btn-custom shadow mt-3" type="submit">Submit</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock body_block %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}
	<section class="temp-margin">
		<div class="container shadow rounded">
			<div class="row">
				<div class="col-sm-5 pl-0">
					<!-- User image, email -->
					<div class="media shadow">
						<img src="{% static "img/brianmwevi.jpg" %}" class="img-fluid rounded" alt="Testing image">
					</div>
				</div>
				<!-- User details -->
				<div class="col-sm-7 bg-light text-center">
					<div class="d-sm-none d-lg-block">
						{% if user.get_full_name %}
							<h4 class="pt-3 font-weight-bold">{{ user.get_full_name }}</h4>
							<h6 class="text-lowercase">@{{ user.first_name }}{{ user.last_name }}</h6>
						{% else %}
							<p><strong>Description</strong></p>
						{% endif %}
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus corporis sequi, maiores distinctio reiciendis neque.</p>
						
					</div>
					<div class="row py-2 pr-3">
						<div class="col-sm-6 shadow rounded p-3 text-left">
							<p class=""><a href="#">Followers</a><span class="ml-3 badge-pill badge-dark">0</span></p>
							<p class=""><a href="#">Following</a><span class="ml-3 badge-pill badge-dark">0</span></p>
							<p><a href="{% url 'writersapp:drafts' %}" class="">Drafts</a><span class="ml-3 badge-pill badge-dark">{{ drafts.count }}</span></p>
							<p><a href="{% url 'writersapp:published' %}" class="">Published</a><span class="ml-3 badge-pill badge-dark">{{ pub.count }}</span></p>
						</div>
						<div class="col-sm-6 shadow rounded p-3 text-left">
							{% if user.get_full_name %}
								<p><strong>Full Name:</strong> {{ user.get_full_name }}</p>
							{% endif %}
							<p><strong>Username:</strong> {{ user.username }}</p>
							<p><strong>Email:</strong> {{ user.email }}</p>
							<p><strong>Date joined: </strong>{{ user.date_joined|date:"D m, Y" }}</p>
							<a href="{% url 'accounts:password_change' %}">Change password?</a>

						</div>
					</div>
					<a href="{% url 'accounts:logout' %}" class="btn btn-custom">Sign out</a>
				</div>
			</div>
			
		</div>
	</section>
{% endblock body_block %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body_block %}
	<section class="home-bg">
		<div class="container">
			<div class="row">
				<div class="col-sm-5 rounded form temp-margin mx-auto">
					<!-- LOG IN FORM -->
					<div id="login" class="form-side shadow gradient p-5 {% if is_user %}
						form-side--front
						{% else %}
							form-side--back
						{% endif %}">
						<h4 class="text-center">Log In</h4>				
						<form id="loginForm" action="{% url 'accounts:register' %}" method="POST">{% csrf_token %}
						{% bootstrap_form login_form %}
						{% if form.errors %}
							<h1>Login form errors</h1>
						{% endif %}
						<div class="text-center">
							<button class="btn btn-custom" type="submit">Log in</button>
						</div>
						</form>
						<div class="text-center pt-2">
						    <p><a href="{% url 'accounts:password_change' %}" class="card-link form-link text-dark"><strong>Forgot password?</strong></a><br><br> Don't have an account?&nbsp;<label class="form-link" onclick="rotateSignup()"><strong>Sign up</strong></label></p>
							<p class="shadow mt-4 text-white">Made with <i class="fa fa-heart text-danger"></i> by <strong>Brian Mwevi</strong><br>
								<a href="https://github.com/BrianMwevi/writer" target="_blank" class="btn btn-md btn-custom text-dark">View on GitHub <i class="fa fa-external-link"></i></a>
							</p>
						</div>
					</div>
					<!-- SINGUP FORM -->
					<div id="signup" class="form-side shadow {% if is_user %}
						form-side--back
						{% else %}
							form-side--front
						{% endif %} gradient p-5">
						<h4 class="text-center">Sign Up</h4>				
						<form id="signupForm" action="{% url 'accounts:register' %}" method="POST">{% csrf_token %}
							{% bootstrap_form signup_form %}
							<div class="text-center">
								<button class="btn btn-custom" type="submit">Sign up</button>
							</div>
						</form>
						<div class="text-center">
						    <p>You have an account?&nbsp;<label class="form-link" onclick="rotateLogin()"><strong>Log in</strong></label></p>
							<p class="shadow text-white">Made with <i class="fa fa-heart text-danger"></i> by <strong>Brian Mwevi</strong><br>
								<a href="https://github.com/BrianMwevi/writer" target="_blank" class="btn btn-md btn-custom text-dark">View on GitHub <i class="fa fa-external-link"></i></a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
			
	</section>
{% endblock body_block %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body_block %}
	<section class="home-bg">
		<div class="container">
		<div class="row">
			<!-- SIGN UP FORM -->
			<div class="col-sm-5 rounded form temp-margin mx-auto">
				<!-- LOG IN FORM -->
				<div id="login" class="form-side shadow gradient p-5 form-side--front">
					<h4 class="text-center">Log In</h4>				
					<form class="user-form pt-3" action="{% url 'accounts:login' %}" method="POST">{% csrf_token %}
					  {% bootstrap_form login_form %}
					  <div class="text-center">
					    <button class="btn btn-custom mt-4" type="submit">Log in</button>
					  </div>
					</form>
					<div class="text-center pt-2">
					    <p>Don't have an account?&nbsp;<label class="form-link" onclick="rotateSingup()">Sign up</label></p>
						<p class="shadow">Made with <i class="fa fa-heart text-danger"></i> by <strong>Brian Mwevi</strong><br>
							<a href="#" target="_blank" class="btn btn-md btn-custom text-dark">View on GitHub <i class="fa fa-external-link"></i></a>
						</p>
					</div>
				</div>
				<div id="signup" class="form-side shadow form-side--back gradient p-5">
					<h4 class="text-center">Sign Up</h4>				
					<form action="{% url 'accounts:signup' %}" class="user-form" method="POST">{% csrf_token %}
						{% bootstrap_form form %}
						<div class="text-center">
							<button class="btn btn-custom mt-4" type="submit">Sign up</button>
							<p>You have an account?&nbsp;<strong class="form-link" onclick="rotateLogin()">Log in</strong></p>
						</div>
					</form>
					<div class="text-center py-1">
						<p class="shadow">Made with <i class="fa fa-heart text-danger"></i> by <strong>Brian Mwevi</strong><br>
							<a href="#" target="_blank" class="btn btn-md btn-custom text-dark">View on GitHub <i class="fa fa-external-link"></i></a>
						</p>
					</div>
				</div>
			</div>

		</div>
	</div>
			
	</section>
{% endblock body_block %}

accounts/templates/accounts/was_login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body_block %}
	<section class="home-bg">
		<div class="container">
		<div class="row">
			<div class="col-sm-5 rounded gradient shadow p-5 temp-margin mx-auto">
				<h4 class="text-center">Log In</h4>				
				<form class="user-form" method="POST">{% csrf_token %}
				  {% bootstrap_form form %}
				  <div class="text-center">
				    <button class="btn btn-custom" type="submit">Log in</button>
				    <p>Already have an account? <a href="{% url 'accounts:login' %}" class="card-link text-primary">Log in</a></p>
				  </div>
				</form>
				<div class="text-center py-1">
					<p class="shadow">Made with <i class="fa fa-heart text-danger"></i> by <strong>Brian Mwevi</strong><br>
						<a href="#" target="_blank" class="btn btn-md btn-custom text-dark">View on GitHub <i class="fa fa-external-link"></i></a>
					</p>
				</div>
			</div>
		</div>
	</div>
	</section>
{% endblock body_block %}