accounts/urls.py
from django.urls import path, re_path
from django.urls import reverse_lazy
from .views import register, password_change, UserProfile
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
	path('register/', register, name='register'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout', kwargs={'next_page':'writersapp:home'}),
	path('password/', password_change, name="password_change"),
	path('profile/', UserProfile.as_view(), name="profile"),
]

writers/urls.py
from django.contrib import admin
from django.urls import path, include

from writersapp.views import PostListView

urlpatterns = [
	path('',PostListView.as_view(), name='home'),
	path('post/', include('writersapp.urls', namespace='writersapp')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    # path('accounts/', include('accounts.passwords.urls')),
]

writersapp/urls.py
from django.urls import path 

from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, DraftListView, PostPublishView,PostPublishedview, CommentView

app_name = "writersapp"

urlpatterns = [
	# path('', PostDetailView.as_view(), name='post_list'),
	path('detail/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
	path('create/', PostCreateView.as_view(), name='post_create'),
	path('drafts/', DraftListView.as_view(), name='drafts'),
	path('update/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
	path('publish/<int:pk>/', PostPublishView.as_view(), name='post_publish'),
	path('published/list/', PostPublishedview.as_view(), name='published'),
	path('delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),
	path('comment/<int:pk>/', CommentView.as_view(), name='comment_create'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Writers | Blog</title>
	<link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
	<link rel="stylesheet" href="{% static "css/style.css" %}">
	<link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static "css/medium-editor.min.css" %}">
	<link rel="stylesheet" href="{% static "css/default.min.css" %}">

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
		<div class="container">
			<a class="navbar-brand" href="{% url 'home' %}">
				<img src="{% static "img/logoblog.png" %}" alt="Logo" style="width:90px">
			</a>
			<button class="navbar-toggler" data-target="#mainNav" data-toggle="collapse"><span class="navbar-toggler-icon"></span></button>
			<div class="collapse navbar-collapse" id="mainNav">
				
				<ul class="navbar-nav ml-auto">

					{% if user.is_authenticated %}					
						{% if post.draft %}
							<li class="nav-item mx-2">
								<form action="{% url 'writersapp:post_publish' pk=post.pk %}" method="POST">{% csrf_token %}
									<button class="btn btn-sm btn-custom">Ready to publish?</button>
								</form>
							</li>
							<div class="list-group list-group-flush popup">
								<li class="nav-link mx-2"><i class="fa fa-ellipsis-h"></i>
									
								</li>
								
							</div>
						{% else %}
						{% if user == post.author %}
							<div class="list-group list-group-flush popup">
								<li class="nav-link mx-2"><i class="fa fa-cog fa-2x" onclick="popupCog()"></i>
									<div id="popupEdit" class="popup-menu">
										<a class="list-group-item list-group-item-action text-left bg-light border-0" href="{% url 'writersapp:post_update' pk=post.pk %}">Edit story</a>									
										<a class="list-group-item list-group-item-action text-left bg-light border-0" href="#">Stats</a>
										<a class="list-group-item list-group-item-action text-left bg-light border-0" href="#">Share link</a>
									</div>
								</li>
							</div>
						{% else %}
							<li class="nav-item mx-2"><a href="" class="nav-link"><i class="fa fa-search"></i></a></li>											
						{% endif %}		
						{% endif %}
						<li class="nav-item mx-2"><a href="" class="nav-link"><i class="fa fa-bell-o"></i></a></li>
						{% if not post.draft %}
							<li class="nav-item mx-2"><a href="" class="nav-link btn btn-sm btn-custom">Upgrade</a></li>
						{% endif %}

						<!-- Popup menu -->
						<div class="list-group list-group-flush popup">
							<img src="{% static "img/brianmwevi.jpg" %}" class="img-fluid rounded-circle" alt="Brian Mwevi" onclick="popMenu()" style="width:40px; height:40px">
								<div id="popupMenu" class="popup-menu">
									<a class="list-group-item list-group-item-action text-left bg-light border-0" href="{% url 'writersapp:post_create' %}"><small>New story</small></a>
									<a class="list-group-item list-group-item-action text-left bg-light border-0" href="{% url 'writersapp:drafts' %}"><small>Drafts</small> <span class="badge badge-info badge-pill">{{ user_draft.count }}</span></a>
									<a class="list-group-item list-group-item-action text-left bg-light border-0" href="{% url 'writersapp:published' %}"><small>Published</small> <span class="badge badge-info badge-pill">{{ user_pub_posts.count }}</span></a>
									<a class="list-group-item list-group-item-action text-left bg-light border-0" href="{% url 'accounts:profile' %}"><small>Profile</small></a>
									<a class="list-group-item list-group-item-action text-left bg-light border-0" href="{% url 'accounts:logout' %}"><small>Sign out</small></a>
								</div>
							</div>
						</div>
					{% else %}
						<li class="nav-item"><a href="{% url 'accounts:register' %}" class="nav-link text-info">Register/Log In</a></li>
					{% endif %}
					
				</ul>
				
			</div>
			
		</div>
		
	</nav>

	{% block body_block %}
	
		<h1>Hello world from base.html. The main base file</h1>
		
		<footer class="bg-secondary text-center">
			
			<p class="m-0 py-4">Created by
				
				<strong>
					
					<a href="https://brianmwevi.github.io" class="card-link">Brian Mwevi</a>
					
				</strong>
				
				<br>
				
				Copyrights &copy; 2018
				
			</p>
					
			<p class="m-0"></p>
			
		</footer>
	
	{% endblock body_block %}
	
	<script src="{% static "js/jquery.min.js" %}"></script>
	
	<script src="{% static "js/popper.min.js" %}"></script>
	
	<script src="{% static "js/bootstrap.min.js" %}"></script>

	<script src="{% static "js/main.js" %}"></script>

	<script src="{% static "js/medium-editor.min.js" %}"></script>



	<script>

		// using jQuery
		var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
		var editor = new MediumEditor('.editable',{
			 disableDoubleReturn: {
         		default:true
	    	},
		});
		// var elements = document.querySelectorAll('.editable'),
	 //    editor = new MediumEditor(elements);


	</script>

	
</body>

</html>
 